import { useRef, useState } from 'react'
import { NavLink, Navigate, Route, Routes, useNavigate } from 'react-router-dom'
import { ArrowDown, ArrowUp, CalendarDays, ChevronDown, ChevronUp, Compass, MapPin, RotateCcw, Search, Sparkles, Trash2, Users } from 'lucide-react'
import './index.css'

const styles = ['Food & culture', 'Nature & adventure', 'Relaxation', 'City break']
const emptyForm = { destination: '', brief: '', travelDate: '', travelers: 'Just me', interests: [] }
const isItinerary = (value) => value && typeof value.title === 'string' && typeof value.summary === 'string' && Array.isArray(value.days) && value.days.length > 0 && value.days.every((day) => typeof day.day === 'string' && typeof day.theme === 'string' && Array.isArray(day.activities) && day.activities.every((activity) => typeof activity === 'string'))

function Layout({ children }) { return <main><nav className="nav shell"><NavLink className="brand" to="/"><span><Compass size={20}/></span>Roamly</NavLink><div className="nav-links"><NavLink to="/">Dashboard</NavLink><NavLink to="/details">Trip details</NavLink><NavLink to="/itinerary">Itinerary</NavLink></div><button className="profile" aria-label="Open profile">KC</button></nav>{children}</main> }

function Dashboard({ itinerary, form }) { const navigate = useNavigate(); return <><section className="dashboard-hero shell"><div><div className="eyebrow"><Sparkles size={15}/> Your intelligent travel companion</div><h1>Travel farther.<br/><em>Plan smarter.</em></h1><p>Create structured, editable trip plans from a few details and a free-form travel brief.</p><button className="primary" onClick={() => navigate('/details')}>Plan a new trip <span>-&gt;</span></button></div><aside className="dashboard-orb"><Sparkles size={42}/><span>AI-powered<br/>itineraries</span></aside></section><section className="shell dashboard-section"><div className="saved-head"><div><p className="overline">YOUR WORKSPACE</p><h2>{itinerary ? 'Your latest trip' : 'Start with a trip idea'}</h2></div></div>{itinerary ? <button className="latest-trip" onClick={() => navigate('/itinerary')}><div><p>{form.destination}</p><h3>{itinerary.title}</h3><span>{itinerary.days.length} days ready to edit</span></div><span>-&gt;</span></button> : <div className="empty-state"><Sparkles size={25}/><strong>No itinerary yet</strong><span>Add your destination and a short trip description, then generate an editable plan.</span><button className="outline" onClick={() => navigate('/details')}>Add trip details</button></div>}</section></> }

function Details({ form, setForm, generate, loading, error }) { const navigate = useNavigate(); const update = (key, value) => setForm((current) => ({ ...current, [key]: value })); const toggle = (style) => update('interests', form.interests.includes(style) ? form.interests.filter((item) => item !== style) : [...form.interests, style]); async function submit(event) { const success = await generate(event); if (success) navigate('/itinerary') }
  return <section className="planner-wrap page-wrap"><div className="planner shell"><div className="page-kicker">STEP 1 OF 2</div><div className="section-heading"><span className="mini-icon"><MapPin size={19}/></span><div><h2>Tell us about your trip</h2><p>These details guide the structured itinerary returned by the planner.</p></div></div><form onSubmit={submit}><label>Destination<div className="field"><MapPin size={19}/><input value={form.destination} onChange={(e) => update('destination', e.target.value)} placeholder="City or country" required/><Search size={18}/></div></label><label>Describe your ideal trip <small>free-form input</small><textarea className="trip-brief" value={form.brief} onChange={(e) => update('brief', e.target.value)} placeholder="For example: I want a relaxed food-focused trip with scenic walks and local culture. Avoid packed schedules."/></label><div className="field-grid"><label>When are you going?<div className="field"><CalendarDays size={18}/><input type="date" value={form.travelDate} onChange={(e) => update('travelDate', e.target.value)}/></div></label><label>Who is coming along?<div className="field"><Users size={18}/><select value={form.travelers} onChange={(e) => update('travelers', e.target.value)}><option>Just me</option><option>2 travelers</option><option>3-4 travelers</option><option>5+ travelers</option></select></div></label></div><label>Trip style <small>optional</small><div className="chips">{styles.map((style) => <button className={form.interests.includes(style) ? 'selected' : ''} type="button" key={style} onClick={() => toggle(style)}>{style}</button>)}</div></label><button className="generate" type="submit" disabled={loading}><Sparkles size={18}/>{loading ? 'Creating your trip...' : 'Generate itinerary'}</button></form>{error && <div className="error-message"><span>{error}</span><button type="button" onClick={(event) => submit(event)}><RotateCcw size={15}/> Retry</button></div>}</div></section> }

function Itinerary({ itinerary, setItinerary, loading, error, regenerate }) { const navigate = useNavigate(); const [expanded, setExpanded] = useState(new Set([0])); const toggleDay = (index) => setExpanded((current) => { const next = new Set(current); next.has(index) ? next.delete(index) : next.add(index); return next }); const change = (dayIndex, update) => setItinerary((current) => ({ ...current, days: current.days.map((day, index) => index === dayIndex ? { ...day, activities: update(day.activities) } : day) })); const move = (dayIndex, stopIndex, direction) => change(dayIndex, (items) => { const target = stopIndex + direction; if (target < 0 || target >= items.length) return items; const next = [...items]; [next[stopIndex], next[target]] = [next[target], next[stopIndex]]; return next }); const remove = (dayIndex, stopIndex) => change(dayIndex, (items) => items.filter((_, index) => index !== stopIndex));
  if (!itinerary) return <section className="saved shell page-wrap"><div className="empty-state"><Sparkles size={25}/><strong>{loading ? 'Creating your itinerary...' : 'No itinerary to show'}</strong><span>{error || 'Complete your trip details and we will organize your stops here.'}</span><button className="outline" onClick={() => navigate('/details')}>Go to trip details</button></div></section>
  return <section className="saved shell page-wrap"><div className="saved-head"><div><p className="overline">STEP 2 OF 2</p><h2>Interactive itinerary</h2></div><button className="outline" onClick={regenerate} disabled={loading}><RotateCcw size={16}/> Regenerate</button></div><section className="itinerary interactive"><div className="itinerary-title"><Sparkles size={18}/><div><h3>{itinerary.title}</h3><p>{itinerary.summary}</p></div></div>{itinerary.days.map((day, dayIndex) => <article className="day-card" key={`${day.day}-${dayIndex}`}><button className="day-toggle" onClick={() => toggleDay(dayIndex)}><b>{day.day}</b><strong>{day.theme}</strong>{expanded.has(dayIndex) ? <ChevronUp size={18}/> : <ChevronDown size={18}/>}</button>{expanded.has(dayIndex) && <div className="stops">{day.activities.length === 0 ? <p className="no-stops">No stops left for this day.</p> : day.activities.map((activity, stopIndex) => <div className="stop" key={`${activity}-${stopIndex}`}><span>{activity}</span><div><button title="Move up" disabled={stopIndex === 0} onClick={() => move(dayIndex, stopIndex, -1)}><ArrowUp size={14}/></button><button title="Move down" disabled={stopIndex === day.activities.length - 1} onClick={() => move(dayIndex, stopIndex, 1)}><ArrowDown size={14}/></button><button title="Remove stop" className="remove" onClick={() => remove(dayIndex, stopIndex)}><Trash2 size={14}/></button></div></div>)}</div>}</article>)}</section></section> }

function App() { const [form, setForm] = useState(emptyForm); const [itinerary, setItinerary] = useState(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const controllerRef = useRef(null); async function generate(event) { event?.preventDefault(); controllerRef.current?.abort(); const controller = new AbortController(); controllerRef.current = controller; setLoading(true); setError(''); const timeout = setTimeout(() => controller.abort(), 20000); try { const response = await fetch('/api/itinerary', { method:'POST', headers:{ 'Content-Type':'application/json' }, body:JSON.stringify({ destination:form.destination, brief:form.brief, dates:form.travelDate || 'Flexible dates', travelers:form.travelers, interests:form.interests }), signal:controller.signal }); const data = await response.json().catch(() => { throw new Error('The server returned an unreadable response. Please retry.') }); if (!response.ok) throw new Error(data.error || 'Unable to create an itinerary.'); if (!isItinerary(data)) throw new Error('The itinerary data was incomplete. Please retry.'); if (controllerRef.current === controller) setItinerary(data); return true } catch (requestError) { if (controllerRef.current === controller) setError(requestError.name === 'AbortError' ? 'The request took too long. Please retry.' : requestError.message || 'Something went wrong.'); return false } finally { clearTimeout(timeout); if (controllerRef.current === controller) setLoading(false) } }
  return <Layout><Routes><Route path="/" element={<Dashboard itinerary={itinerary} form={form}/>}/><Route path="/details" element={<Details form={form} setForm={setForm} generate={generate} loading={loading} error={error}/>}/><Route path="/itinerary" element={<Itinerary itinerary={itinerary} setItinerary={setItinerary} loading={loading} error={error} regenerate={generate}/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></Layout> }
export default App
